/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uv.expressit.view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;



/**
 *
 * @author josuecg
 */
public class GUIInicio extends javax.swing.JFrame {

    int contador = 0;
    /**
     * Creates new form GUIInicio
     */
    public GUIInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        bg = new javax.swing.JPanel();
        mainSection = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnInicio = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnPerfil = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnConfigurarPerfil = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        profileSection = new javax.swing.JPanel();
        btnAñadirBoton = new javax.swing.JButton();
        bgContent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        content = new javax.swing.JPanel();
        txtBuscador = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnTuitear = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1080, 720));
        setMaximumSize(null);
        setResizable(false);

        bg.setBackground(new java.awt.Color(20, 20, 21));
        bg.setBorder(null);
        bg.setRequestFocusEnabled(false);
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainSection.setBackground(new java.awt.Color(13, 13, 13));
        mainSection.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        mainSection.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 33)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Express It");
        mainSection.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 70));

        btnInicio.setBackground(new java.awt.Color(13, 13, 13));
        btnInicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Inicio");

        javax.swing.GroupLayout btnInicioLayout = new javax.swing.GroupLayout(btnInicio);
        btnInicio.setLayout(btnInicioLayout);
        btnInicioLayout.setHorizontalGroup(
            btnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        btnInicioLayout.setVerticalGroup(
            btnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainSection.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 74, -1, 60));

        btnPerfil.setBackground(new java.awt.Color(13, 13, 13));
        btnPerfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Perfil");

        javax.swing.GroupLayout btnPerfilLayout = new javax.swing.GroupLayout(btnPerfil);
        btnPerfil.setLayout(btnPerfilLayout);
        btnPerfilLayout.setHorizontalGroup(
            btnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        btnPerfilLayout.setVerticalGroup(
            btnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainSection.add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 134, 220, 60));

        btnConfigurarPerfil.setBackground(new java.awt.Color(13, 13, 13));
        btnConfigurarPerfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Configuración");

        javax.swing.GroupLayout btnConfigurarPerfilLayout = new javax.swing.GroupLayout(btnConfigurarPerfil);
        btnConfigurarPerfil.setLayout(btnConfigurarPerfilLayout);
        btnConfigurarPerfilLayout.setHorizontalGroup(
            btnConfigurarPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnConfigurarPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        btnConfigurarPerfilLayout.setVerticalGroup(
            btnConfigurarPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnConfigurarPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainSection.add(btnConfigurarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 193, 220, 60));

        btnCerrarSesion.setBackground(new java.awt.Color(120, 0, 14));
        btnCerrarSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cerrar sesión");

        javax.swing.GroupLayout btnCerrarSesionLayout = new javax.swing.GroupLayout(btnCerrarSesion);
        btnCerrarSesion.setLayout(btnCerrarSesionLayout);
        btnCerrarSesionLayout.setHorizontalGroup(
            btnCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCerrarSesionLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel6)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        btnCerrarSesionLayout.setVerticalGroup(
            btnCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCerrarSesionLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        mainSection.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 220, 70));

        bg.add(mainSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 720));

        profileSection.setBackground(new java.awt.Color(13, 13, 13));

        btnAñadirBoton.setText("Añadir boton");
        btnAñadirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profileSectionLayout = new javax.swing.GroupLayout(profileSection);
        profileSection.setLayout(profileSectionLayout);
        profileSectionLayout.setHorizontalGroup(
            profileSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileSectionLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btnAñadirBoton)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        profileSectionLayout.setVerticalGroup(
            profileSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileSectionLayout.createSequentialGroup()
                .addContainerGap(532, Short.MAX_VALUE)
                .addComponent(btnAñadirBoton)
                .addGap(161, 161, 161))
        );

        bg.add(profileSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 280, 720));

        bgContent.setBackground(new java.awt.Color(13, 13, 13));
        bgContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        content.setBackground(new java.awt.Color(13, 13, 13));
        content.setAutoscrolls(true);
        content.setLayout(new javax.swing.BoxLayout(content, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(content);

        bgContent.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 640, 590));

        txtBuscador.setBackground(new java.awt.Color(20, 20, 21));
        txtBuscador.setFont(new java.awt.Font("DejaVu Sans", 2, 18)); // NOI18N
        txtBuscador.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscador.setText("Buscar...");
        txtBuscador.setBorder(new LineBorder(Color.BLACK));
        txtBuscador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscadorMouseClicked(evt);
            }
        });
        txtBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyTyped(evt);
            }
        });
        bgContent.add(txtBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 530, 40));

        jPanel2.setBackground(new java.awt.Color(0, 116, 158));
        jPanel2.setPreferredSize(new java.awt.Dimension(110, 34));

        jLabel7.setBackground(new java.awt.Color(0, 116, 158));
        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Buscar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bgContent.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 100, 30));

        bg.add(bgContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 0, 660, -1));

        btnTuitear.setBackground(new java.awt.Color(0, 116, 158));
        btnTuitear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTuitearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTuitearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTuitearMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Express it");

        javax.swing.GroupLayout btnTuitearLayout = new javax.swing.GroupLayout(btnTuitear);
        btnTuitear.setLayout(btnTuitearLayout);
        btnTuitearLayout.setHorizontalGroup(
            btnTuitearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTuitearLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jLabel1)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        btnTuitearLayout.setVerticalGroup(
            btnTuitearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTuitearLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        bg.add(btnTuitear, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 650, 650, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirBotonActionPerformed
        contador = contador + 10;
        BorderLayout borderLayout = new BorderLayout();
        //Border lineBorder = BorderFactory.createLineBorder(Color.BLACK,4);
        
        JPanel pane = new JPanel();
        JPanel paneBotones = new JPanel();
        
        JLabel btnMeGusta = new JLabel("Me gusta");
        JLabel btnComentar = new JLabel("Comentarios");
        btnMeGusta.setFont(new Font("SansSerif", Font.BOLD, 16));
        btnComentar.setFont(new Font("SansSerif", Font.BOLD, 16));
        btnMeGusta.setForeground(Color.white);
        btnComentar.setForeground(Color.white);
        
        JLabel lbContadorMeGusta = new JLabel("     "+"30"+"     ");
        lbContadorMeGusta.setForeground(Color.white);
        JLabel lbContadorComentarios = new JLabel("     "+"10"+"     ");
        lbContadorComentarios.setForeground(Color.white);
        JTextArea areaText = new JTextArea("Use this to specify where excess space in a layout should go. Think of it as semi-wet glue -- stretchy and expandable, yet taking up no space unless you pull apart the components that it's sticking to. For example, by putting horizontal glue between two components in a left-to-right box, you make any extra space go between those components, instead of to the right of all the components. Here's an example of making the space in a left-to-right box go between two components, instead of to the right of the components: ");
        areaText.setLineWrap(true);
        areaText.setForeground(Color.white);
        areaText.setBackground(Color.decode("#29292B"));
        areaText.setEditable(false);
        JLabel lbUsuarioTuit = new JLabel("Publicado por: @capistran");
        lbUsuarioTuit.setForeground(Color.white);
        lbUsuarioTuit.setFont(new Font("SansSerif", Font.BOLD, 20));
        areaText.setFont(new Font("SansSerif", Font.PLAIN, 16));
        areaText.setPreferredSize(new Dimension(200,200));
        
        paneBotones.setLayout(new BoxLayout(paneBotones, BoxLayout.X_AXIS));
        paneBotones.add(btnMeGusta);
        paneBotones.add(lbContadorMeGusta);
        paneBotones.setBackground(Color.decode("#141415"));
        
        paneBotones.add(btnComentar);
        paneBotones.add(lbContadorComentarios);
        paneBotones.add(Box.createHorizontalGlue());
        
        pane.setLayout(borderLayout);
        pane.add(lbUsuarioTuit, BorderLayout.PAGE_START);
        pane.add(areaText, BorderLayout.CENTER);
        pane.add(paneBotones, BorderLayout.PAGE_END );
        pane.setBackground(Color.decode("#141415"));
        
        //pane.setBorder(lineBorder);
        this.content.add(pane);
        this.content.add(Box.createRigidArea(new Dimension(15,15)));
        content.updateUI();
    }//GEN-LAST:event_btnAñadirBotonActionPerformed

    private void btnTuitearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTuitearMouseClicked
        GUIAñadirEntrada nuevaEntrada = new GUIAñadirEntrada();
        nuevaEntrada.setVisible(true);
    }//GEN-LAST:event_btnTuitearMouseClicked

    private void btnTuitearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTuitearMouseEntered
        btnTuitear.setBackground(Color.decode("#00b0f0"));
    }//GEN-LAST:event_btnTuitearMouseEntered

    private void btnTuitearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTuitearMouseExited
       btnTuitear.setBackground(Color.decode("#00749E"));
    }//GEN-LAST:event_btnTuitearMouseExited

    private void btnCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseEntered
        btnCerrarSesion.setBackground(Color.decode("#A7000E"));
    }//GEN-LAST:event_btnCerrarSesionMouseEntered

    private void btnCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseExited
        btnCerrarSesion.setBackground(Color.decode("#78000E"));
    }//GEN-LAST:event_btnCerrarSesionMouseExited

    private void txtBuscadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscadorMouseClicked
        this.txtBuscador.setText("");
        this.txtBuscador.setForeground(Color.WHITE);
        this.txtBuscador.setFont(new Font("DejaVu Sans", Font.PLAIN, 18));
    }//GEN-LAST:event_txtBuscadorMouseClicked

    private void txtBuscadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyTyped
       if(txtBuscador.getText().equals("Buscar...")){
           txtBuscador.setText("");
       }
    }//GEN-LAST:event_txtBuscadorKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bgContent;
    private javax.swing.JButton btnAñadirBoton;
    private javax.swing.JPanel btnCerrarSesion;
    private javax.swing.JPanel btnConfigurarPerfil;
    private javax.swing.JPanel btnInicio;
    private javax.swing.JPanel btnPerfil;
    private javax.swing.JPanel btnTuitear;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel mainSection;
    private javax.swing.JPanel profileSection;
    private javax.swing.JTextField txtBuscador;
    // End of variables declaration//GEN-END:variables
}
